"""
Public connector catalog — the definitive list of connector types
available in Agentix.  This drives both the admin UI and the CLI
`agentix connector list` command.
"""
from __future__ import annotations

CATALOG: list[dict] = [
    # ── Developer ──────────────────────────────────────────────────────────
    {
        "type": "github",
        "display_name": "GitHub",
        "description": "Create issues, pull requests, review code, and manage repositories.",
        "category": "developer",
        "icon": "🐙",
        "auth_type": "api_key",
        "required_config": ["token"],
        "optional_config": ["default_owner", "default_repo", "base_url"],
        "actions": [
            "create_issue", "get_issue", "add_comment",
            "create_pull_request", "list_repos", "search_code", "get_file",
        ],
        "docs_url": "https://docs.agentix.dev/connectors/github",
    },
    {
        "type": "jira",
        "display_name": "Jira",
        "description": "Create and manage Jira issues, projects, and sprints.",
        "category": "developer",
        "icon": "🎯",
        "auth_type": "api_key",
        "required_config": ["base_url", "email", "api_token"],
        "optional_config": ["default_project"],
        "actions": ["create_issue", "get_issue", "update_issue", "add_comment", "list_projects"],
        "docs_url": "https://docs.agentix.dev/connectors/jira",
    },
    {
        "type": "linear",
        "display_name": "Linear",
        "description": "Create and manage issues, projects, and cycles in Linear.",
        "category": "developer",
        "icon": "📐",
        "auth_type": "api_key",
        "required_config": ["api_key"],
        "optional_config": ["default_team_id"],
        "actions": ["create_issue", "get_issue", "update_issue", "list_teams", "list_issues"],
        "docs_url": "https://docs.agentix.dev/connectors/linear",
    },
    # ── Messaging ──────────────────────────────────────────────────────────
    {
        "type": "slack",
        "display_name": "Slack",
        "description": "Post messages, create channels, and interact with your Slack workspace.",
        "category": "messaging",
        "icon": "💬",
        "auth_type": "api_key",
        "required_config": ["bot_token"],
        "optional_config": ["default_channel"],
        "actions": ["post_message", "create_channel", "get_user_info", "list_channels", "upload_file"],
        "docs_url": "https://docs.agentix.dev/connectors/slack",
    },
    {
        "type": "discord",
        "display_name": "Discord",
        "description": "Post messages, manage roles, and interact with Discord guilds.",
        "category": "messaging",
        "icon": "🎮",
        "auth_type": "api_key",
        "required_config": ["bot_token"],
        "optional_config": ["default_channel_id", "guild_id"],
        "actions": ["send_message", "create_thread", "list_channels", "get_guild_info"],
        "docs_url": "https://docs.agentix.dev/connectors/discord",
    },
    {
        "type": "sendgrid",
        "display_name": "SendGrid",
        "description": "Send transactional and template-based emails via SendGrid.",
        "category": "messaging",
        "icon": "📧",
        "auth_type": "api_key",
        "required_config": ["api_key"],
        "optional_config": ["from_email", "from_name"],
        "actions": ["send_email", "send_template", "add_contact", "get_stats"],
        "docs_url": "https://docs.agentix.dev/connectors/sendgrid",
    },
    {
        "type": "twilio",
        "display_name": "Twilio",
        "description": "Send SMS messages, make calls, and manage phone numbers.",
        "category": "messaging",
        "icon": "📱",
        "auth_type": "api_key",
        "required_config": ["account_sid", "auth_token"],
        "optional_config": ["from_number"],
        "actions": ["send_sms", "make_call", "list_messages", "get_message"],
        "docs_url": "https://docs.agentix.dev/connectors/twilio",
    },
    # ── CRM ───────────────────────────────────────────────────────────────
    {
        "type": "hubspot",
        "display_name": "HubSpot",
        "description": "Manage contacts, deals, and companies in HubSpot CRM.",
        "category": "crm",
        "icon": "🧡",
        "auth_type": "api_key",
        "required_config": ["api_key"],
        "optional_config": [],
        "actions": ["create_contact", "get_contact", "update_contact", "create_deal", "search_contacts"],
        "docs_url": "https://docs.agentix.dev/connectors/hubspot",
    },
    {
        "type": "salesforce",
        "display_name": "Salesforce",
        "description": "Create leads, update opportunities, and query Salesforce records.",
        "category": "crm",
        "icon": "☁️",
        "auth_type": "oauth2",
        "required_config": ["client_id", "client_secret", "username", "password"],
        "optional_config": ["instance_url", "sandbox"],
        "actions": ["create_lead", "get_record", "update_record", "query_soql", "create_case"],
        "docs_url": "https://docs.agentix.dev/connectors/salesforce",
    },
    # ── Finance ───────────────────────────────────────────────────────────
    {
        "type": "stripe",
        "display_name": "Stripe",
        "description": "Manage customers, invoices, subscriptions, and payment intents.",
        "category": "finance",
        "icon": "💳",
        "auth_type": "api_key",
        "required_config": ["api_key"],
        "optional_config": [],
        "actions": [
            "create_customer", "get_customer", "create_invoice",
            "list_payments", "create_payment_intent",
        ],
        "docs_url": "https://docs.agentix.dev/connectors/stripe",
    },
    # ── Productivity ──────────────────────────────────────────────────────
    {
        "type": "notion",
        "display_name": "Notion",
        "description": "Create and update pages and query databases in Notion.",
        "category": "productivity",
        "icon": "📝",
        "auth_type": "api_key",
        "required_config": ["token"],
        "optional_config": ["default_database_id"],
        "actions": ["create_page", "update_page", "get_page", "query_database", "append_block"],
        "docs_url": "https://docs.agentix.dev/connectors/notion",
    },
    {
        "type": "google_sheets",
        "display_name": "Google Sheets",
        "description": "Read and write data in Google Sheets spreadsheets.",
        "category": "google",
        "icon": "📊",
        "auth_type": "oauth2",
        "required_config": ["credentials_json"],
        "optional_config": ["access_token", "default_spreadsheet_id"],
        "actions": ["get_values", "set_values", "append_rows", "create_spreadsheet", "list_sheets", "add_sheet", "clear_range"],
        "docs_url": "https://docs.agentix.dev/connectors/google-sheets",
    },
    # ── Google ────────────────────────────────────────────────────────────────
    {
        "type": "gmail",
        "display_name": "Gmail",
        "description": "Send, search, and manage emails via Google Gmail API.",
        "category": "google",
        "icon": "📧",
        "auth_type": "oauth2",
        "required_config": ["credentials_json"],
        "optional_config": ["access_token"],
        "actions": ["send_email", "list_emails", "get_email", "search_emails", "manage_labels"],
        "docs_url": "https://docs.agentix.dev/connectors/gmail",
    },
    {
        "type": "google_drive",
        "display_name": "Google Drive",
        "description": "List, upload, download, and manage files in Google Drive.",
        "category": "google",
        "icon": "📁",
        "auth_type": "oauth2",
        "required_config": ["credentials_json"],
        "optional_config": ["access_token"],
        "actions": ["list_files", "get_file", "download_file", "create_folder", "upload_file", "delete_file", "share_file"],
        "docs_url": "https://docs.agentix.dev/connectors/google-drive",
    },
    {
        "type": "google_calendar",
        "display_name": "Google Calendar",
        "description": "Create, update, and manage Google Calendar events and meetings.",
        "category": "google",
        "icon": "📅",
        "auth_type": "oauth2",
        "required_config": ["credentials_json"],
        "optional_config": ["access_token", "default_calendar_id", "default_timezone"],
        "actions": ["list_events", "get_event", "create_event", "update_event", "delete_event", "list_calendars"],
        "docs_url": "https://docs.agentix.dev/connectors/google-calendar",
    },
    # ── Database ──────────────────────────────────────────────────────────
    {
        "type": "airtable",
        "display_name": "Airtable",
        "description": "Read and write records in Airtable bases and tables.",
        "category": "database",
        "icon": "🗄️",
        "auth_type": "api_key",
        "required_config": ["api_key", "base_id"],
        "optional_config": ["default_table"],
        "actions": ["list_records", "get_record", "create_record", "update_record", "delete_record"],
        "docs_url": "https://docs.agentix.dev/connectors/airtable",
    },
    {
        "type": "postgres",
        "display_name": "PostgreSQL",
        "description": "Execute queries and manage data in a PostgreSQL database.",
        "category": "database",
        "icon": "🐘",
        "auth_type": "basic",
        "required_config": ["host", "database", "user", "password"],
        "optional_config": ["port", "ssl"],
        "actions": ["query", "execute", "get_schema", "list_tables"],
        "docs_url": "https://docs.agentix.dev/connectors/postgres",
    },
    # ── Custom ────────────────────────────────────────────────────────────
    {
        "type": "webhook",
        "display_name": "Custom Webhook",
        "description": "Call any HTTP/HTTPS endpoint with custom headers, method, and body.",
        "category": "custom",
        "icon": "🔗",
        "auth_type": "none",
        "required_config": ["url"],
        "optional_config": ["method", "headers", "auth_header", "verify_ssl"],
        "actions": ["call"],
        "docs_url": "https://docs.agentix.dev/connectors/webhook",
    },
    {
        "type": "openapi",
        "display_name": "OpenAPI / Swagger",
        "description": "Auto-generate tools from any OpenAPI 3.x specification URL.",
        "category": "custom",
        "icon": "📋",
        "auth_type": "api_key",
        "required_config": ["spec_url"],
        "optional_config": ["api_key", "base_url", "allowed_operations"],
        "actions": ["dynamic"],
        "docs_url": "https://docs.agentix.dev/connectors/openapi",
    },
]

# Quick lookup by type name
CATALOG_BY_TYPE: dict[str, dict] = {c["type"]: c for c in CATALOG}

# Unique category list (sorted)
CATEGORIES: list[str] = sorted({c["category"] for c in CATALOG})
